version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    networks:
      - dev-network
  test-db:
    image: postgres:13
    ports:
     - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    networks:
      - test-network
networks:
  dev-network:
  test-network: